import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

import NavBar from "./homeComponents/navbar/navBar";
import Footer from "./homeComponents/footer";

// const inter = Inter({ subsets: ["latin"] });

import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#F1FAEE] ${roboto.className}`}>
        <NavBar />
        {children}
        <Footer />
        <div className="h-[5vh] flex justify-center items-center bg-[#F1FAEE]">
          <span className="font-bold mr-[0.4rem]">
            Century Education Academy
          </span>
          c All rights reserved | Designed and Developed by Shikhar Chand
          ThaQuri.
        </div>
      </body>
    </html>
  );
}
